#!/bin/bash
# Laravel Install

function new_iterm_tab
{
	osascript -e 'tell application "iTerm" to activate' \
	-e 'tell application "System Events" to tell process "iTerm" to keystroke "d" using command down' \
	-e 'tell application "System Events" to tell process "iTerm" to keystroke "cd $HTD/Laravel"' \
	-e 'tell application "System Events" to tell process "iTerm" to key code 52'
}

function laravel_install
{
	# Set local variables 
	local directory_name=$1
	local db_name=$2
	local project_root="$HTD/Laravel/$directory_name"

	# Check if variables exist
	if [ -z "$directory_name" ]; then
		echo "Need directory_name"
		exit
	fi
	if [ -z "$db_name" ]; then
		echo "Need db_name"
		exit
	fi

	# Check if directory exists, remove and enter
	if [ -d "$directory_name" ]; then
		echo "$sudo_pwd" | sudo rm -rf "$directory_name"
	fi

	# Enter laravel folder and create project with name
	cd "$HTD/Laravel/"
	laravel new $directory_name
	cd "$directory_name"
	composer.phar install

	# Change env.example name and generate key
	mv ".env.example" ".env"
	php artisan key:generate

	# Install EBM BP
	cd "resources/assets/"
	git clone git@github.com:EasyBoxModel/EBM.git

	# RM EBM .git folder and move files to parent folder
	cd EBM
	rm -rf .git/ app/ .github/ Gruntfile.js package.json 
 	# find . -maxdepth 1 -type f -execdir mv -nv -- {} .. \;
 	# find . -maxdepth 1 -type d -execdir mv -nv -- {} .. \;

 	# Remove EBM clone empty folder
	# cd ..
	# rm -rf EBM

	# Move EBM .gitignore to root folder
	mv .gitignore "$project_root"
	mv README.md "$project_root"
	cd "$project_root"

	# Copy bp_Laravel5 layout files
	cp -R "$HTD/Laravel/bp_Laravel5/resources/views/includes" "resources/views/"
	cp -R "$HTD/Laravel/bp_Laravel5/resources/views/layout.blade.php" "resources/views/"
	cp -R "$HTD/Laravel/bp_Laravel5/resources/views/welcome.blade.php" "resources/views/"
	cp -R "$HTD/Laravel/bp_Laravel5/Gruntfile.js" "./"
	cp -R "$HTD/Laravel/bp_Laravel5/package.json" "./"
	cp -R "$HTD/Laravel/bp_Laravel5/config/database.php" "config/"
	
	# Replace some file placeholder names with local vars
	sed -i '' "s/DB_NAME/$db_name/g" "config/database.php"

	# New git - new sublime text 
	git init
	stt

	# Install grunt deps
	echo $sudo_pwd | sudo -S npm install

	# Create database
	mysql -e "CREATE DATABASE $db_name; exit;"

	new_iterm_tab

	# Start localhost:8000
	php artisan serve -q
}

laravel_install $1 $2