#!/bin/bash
# Laravel Install

function new_iterm_tab
{
	osascript -e 'tell application "iTerm" to activate' \
	-e 'tell application "System Events" to tell process "iTerm" to keystroke "d" using command down' \
	-e 'tell application "System Events" to tell process "iTerm" to keystroke "cd $p/Laravel"' \
	-e 'tell application "System Events" to tell process "iTerm" to key code 52'
}

function laravel_install
{
	# Set local variables 
	local directory_name=$1
	local db_name=$2
	local project_root="$p/Laravel/$directory_name"
	local resources_path="resources/assets"
	local resources_esc_path="resources\/assets"

	# Check if variables exist
	if [ -z "$directory_name" ]; then
		echo "Need directory_name"
		exit
	fi
	if [ -z "$db_name" ]; then
		echo "Need db_name"
		exit
	fi

	# Check if directory exists, remove and enter
	if [ -d "$directory_name" ]; then
		echo "$sudo_pwd" | sudo rm -rf "$directory_name"
	fi

	# Enter laravel folder and create project with name
	cd "$p/Laravel/"
	laravel new $directory_name
	cd "$directory_name"
	composer install

	# Change env.example name and generate key
	mv ".env.example" ".env"
	php artisan key:generate

	# Install EBM BP
	cd "$resources_path"
	rm -rf js sass
	git clone git@github.com:EasyBoxModel/EBM.git .

	# Move EBM files to project root folder
	rm -rf .git .github
	mv gulpfile.js "$project_root"
	mv .editorconfig "$project_root"
	mv .gitignore "$project_root"
	mv package.json "$project_root"
	
	cd "$project_root"

	# Update gulpfile and scss deps to update laravel assets folder
	sed -i '' "s/SRC_FOLDER/$resources_esc_path/g" "gulpfile.js"
	sed -i '' "s/SRC_FOLDER/$resources_esc_path/g" "$resources_path/sass/global.scss"
	sed -i '' "s/SRC_FOLDER/$resources_esc_path/g" "$resources_path/sass/example.scss"
	sed -i '' "s/SRC_FOLDER/$resources_esc_path/g" "$resources_path/sass/_ebm-imports-reference.scss"

	# Build login/register
	php artisan make:auth

	# Copy bp_Laravel5 layout files
	cp -R "$p/Laravel/bp_Laravel5/resources/views/includes" "resources/views/"
	cp -R "$p/Laravel/bp_Laravel5/resources/views/bp_layout.blade.php" "resources/views/"
	cp -R "$p/Laravel/bp_Laravel5/resources/views/bp_welcome.blade.php" "resources/views/"
	cp -R "$p/Laravel/bp_Laravel5/app/User.php" "app/"
	cp -R "$p/Laravel/bp_Laravel5/app/Services" "app/"
	cp -R "$p/Laravel/bp_Laravel5/app/Http/Controllers/RegistrationController.php" "app/Http/Controllers/"
	cp -R "$p/Laravel/bp_Laravel5/database/migrations/bp_users-migration.php" "database/migrations/"
	cp -R "$p/Laravel/bp_Laravel5/config/database.php" "config/"

	# Replace some file placeholder names with local vars
	sed -i '' "s/DB_NAME/$db_name/g" "config/database.php"
	sed -i '' "s/DB_DATABASE=homestead/DB_DATABASE=$db_name/g" ".env"
	sed -i '' "s/DB_USERNAME=homestead/DB_USERNAME=root/g" ".env"
	sed -i '' "s/DB_PASSWORD=secret/DB_PASSWORD=root/g" ".env"

	# New git - new sublime text 
	git init
	stt

	# Install gulp deps
	npm install

	# Create database
	mysql -e "CREATE DATABASE $db_name; exit;"

	new_iterm_tab
}

laravel_install $1 $2